config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :borrowings
  resources :users
  resources :books

  get 'books/available_books', to: 'books#available_books'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "books#index"
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user
  belongs_to :book

  
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :set_borrowing, only: %i[ show edit update destroy ]

  # GET /borrowings or /borrowings.json
  def index
    @borrowings = Borrowing.all
  end

  # GET /borrowings/1 or /borrowings/1.json
  def show
  end

  # GET /borrowings/new
  def new
    @borrowing = Borrowing.new
  end

  # GET /borrowings/1/edit
  def edit
  end

  # POST /borrowings or /borrowings.json
  def create
    @borrowing = Borrowing.new(borrowing_params)

    respond_to do |format|
      if @borrowing.save
        format.html { redirect_to @borrowing, notice: "Borrowing was successfully created." }
        format.json { render :show, status: :created, location: @borrowing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowings/1 or /borrowings/1.json
  def update
    respond_to do |format|
      if @borrowing.update(borrowing_params)
        format.html { redirect_to @borrowing, notice: "Borrowing was successfully updated." }
        format.json { render :show, status: :ok, location: @borrowing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowings/1 or /borrowings/1.json
  def destroy
    @borrowing.destroy!

    respond_to do |format|
      format.html { redirect_to borrowings_path, status: :see_other, notice: "Borrowing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrowing
      @borrowing = Borrowing.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def borrowing_params
      params.expect(borrowing: [ :user_id, :book_id, :due_date ])
    end
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/borrowings/_borrowing.html.erb
<div id="<%= dom_id borrowing %>">
  <p>
    <strong>User:</strong>
    <%= borrowing.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= borrowing.book_id %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= borrowing.due_date %>
  </p>

</div>

app/views/borrowings/_form.html.erb
<%= form_with(model: borrowing) do |form| %>
  <% if borrowing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(borrowing.errors.count, "error") %> prohibited this borrowing from being saved:</h2>

      <ul>
        <% borrowing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_field :due_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/borrowings/edit.html.erb
<% content_for :title, "Editing borrowing" %>

<h1>Editing borrowing</h1>

<%= render "form", borrowing: @borrowing %>

<br>

<div>
  <%= link_to "Show this borrowing", @borrowing %> |
  <%= link_to "Back to borrowings", borrowings_path %>
</div>

app/views/borrowings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Borrowings" %>

<h1>Borrowings</h1>

<div id="borrowings">
  <% @borrowings.each do |borrowing| %>
    <%= render borrowing %>
    <p>
      <%= link_to "Show this borrowing", borrowing %>
    </p>
  <% end %>
</div>

<%= link_to "New borrowing", new_borrowing_path %>

app/views/borrowings/new.html.erb
<% content_for :title, "New borrowing" %>

<h1>New borrowing</h1>

<%= render "form", borrowing: @borrowing %>

<br>

<div>
  <%= link_to "Back to borrowings", borrowings_path %>
</div>

app/views/borrowings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @borrowing %>

<div>
  <%= link_to "Edit this borrowing", edit_borrowing_path(@borrowing) %> |
  <%= link_to "Back to borrowings", borrowings_path %>

  <%= button_to "Destroy this borrowing", @borrowing, method: :delete %>
</div>