config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :borrowings
  resources :users
  resources :books

  get 'books/available_books', to: 'books#available_books'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "books#index"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrowings
  has_many :users, through: :borrowings

  # validates :title, :author, :isbn, presence: true
  # validates :isbn, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.expect(book: [:title, :author, :isbn, :available ])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="bg-gray-800 shadow rounded-lg px-5 py-3 my-4">
  <p class="text-gray-100 text-lg mb-1 font-bold">
    <%= book.title %><br>
    <em>Written by</em>
    <%= book.author %>
  </p>



  <p class="text-gray-100 text-lg mb-1 font-bold">
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p class="text-gray-100 text-md mb-1 font-bold bg-gray-100 z-50 border">
  
     <%= book.available ? "Borrow" : "" %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.text_field :available %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Books" %>

<h1 class="font-bold">Book</h1>

<div id="books">
  <% @books.each do |book| %>
   <div id="<%= dom_id book %>" class=" bg-gray-800 shadow rounded-lg px-5 py-3 my-4">
      <p class="text-gray-100 text-lg mb-1 font-bold">
       <%= book.title %>
      </p>

      <p>
        <%= link_to "View", book_path(book), class: "hover:bg-gray-700 text-gray-100 font-bold py-2 px-4 rounded" %>
      </p>
    </div>
  <% end %> 
</div>

app/views/books/new.html.erb
<% content_for :title, "New book" %>

<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

    <%= link_to "Edit", edit_book_path(@book), class: "mt-2 rounded-lg py-3 px-5 bg-black text-black inline-block font-medium hover:bg-black" %>
    <%= link_to "Back", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-700 text-black inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", @book, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-black font-medium" %>